baseURL = "https://example.com"
languageCode = "en-us"
title = "LifeOfPassion by Fiona"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "LifeOfPassion"
  description = "Handmade gifts and custom prints"
  message = "Made by me, loved by you."
  hideAutoMenu = false
  
  # Pagination options
  paginate = 3
  multipage = true

  # Dark mode
  darkMode = true

[social]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"